spring.application.name=Bank.com
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_app_db
spring.datasource.username=postgres
spring.datasource.password=jaswanth
spring.jpa.hibernate.ddl-auto=update